"""Add is_public column to wordbooks table

Revision ID: 34cf8b212aeb
Revises: eedd13cd98e9
Create Date: 2025-06-24 15:00:06.179506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cf8b212aeb'
down_revision: Union[str, Sequence[str], None] = 'eedd13cd98e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wordbooks', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wordbooks', 'is_public')
    # ### end Alembic commands ###
