"""add name field to user

Revision ID: 4299fe089341
Revises: 11ec20009f74
Create Date: 2025-07-02 12:15:00.541976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4299fe089341'
down_revision: Union[str, Sequence[str], None] = '11ec20009f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('users', sa.Column('name', sa.String(), nullable=False, server_default='이름없음'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
