"""Add tests relationship to Wordbook model

Revision ID: 4ff30bf9a54f
Revises: 18c8f93cec43
Create Date: 2025-07-07 19:11:58.505604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff30bf9a54f'
down_revision: Union[str, Sequence[str], None] = '18c8f93cec43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
