"""Add part_of_speech and example_sentence to Word model

Revision ID: 528706e915a9
Revises: 8a1f8d241e76
Create Date: 2025-06-25 23:46:07.303853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528706e915a9'
down_revision: Union[str, Sequence[str], None] = '8a1f8d241e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('part_of_speech', sa.String(), nullable=True))
    op.add_column('words', sa.Column('example_sentence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'example_sentence')
    op.drop_column('words', 'part_of_speech')
    # ### end Alembic commands ###
