"""Add is_public column to wordbooks table

Revision ID: eedd13cd98e9
Revises: d54fa1fac7be
Create Date: 2025-06-24 14:57:43.381469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eedd13cd98e9'
down_revision: Union[str, Sequence[str], None] = 'd54fa1fac7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
